config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  resources :users, only: [:index, :show, :edit, :update, :create]
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

  validates :body,
    length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, uniqueness: true

  validates :name,
    length: { minimum: 2, maximum: 20 }

  validates :introduction,
    length: { maximum: 50 }

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpeg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  #before_action :logged_in_user, only: [:edit, :update, :destroy]
  #add_flash_types :success, :info, :warning, :danger

  def after_sign_in_path_for(resource)
    user_path(id: current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
    	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!

  def new

  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if @book.save
    flash[:success] = 'You have created book successfully.'
    redirect_to book_path(@book.id)
   else
    @books = Book.all
    @user = current_user
    render :index
   end
  end

  def edit
    @book = Book.find(params[:id])
     unless @book.user == current_user
        redirect_to books_path
     end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top

  end

  def about

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    #@post_images = @user.post_images
    @books = @user.books
    @new = Book.new
  end

  def edit
    @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user)
      end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:success] = 'You have updated user successfully.'
       redirect_to user_path
    else
      @users = User.all
      render:edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container px-5 px-sm-0">  <!-- この行を追加 -->
  <div class="row">
  <div class="col-md-3">

    <h1>User info</h1>
    <p><%= image_tag user.get_profile_image(100,100) %></p>

    <table class="table">
    <td scope="col">name</td>
    <td>
      <%= user.name %>
    </td>
    <tr>
    <td scope="col">introduction</td>
    <td><%= user.introduction %></td>
    </tr>
    </table>

    <div class="row">
     <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
     <i class="fas fa-user-cog"></i>
     <% end %>
    </div>

  <h1>New book</h1>
  <%= form_with model: book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %><br>
    <%#= f.submit 'Create Book' %>
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  <% end %>
  </div>

app/views/books/edit.html.erb
<p></p>
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: book_path(@book.id), method: :patch do |book| %>
<p>Title</p>
<%= book.text_field :title %>
<p>Body</p>
<%= book.text_area :body %>
<br>
<%#= book.submit 'Update Book' %>
<input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
<p>
  <%= link_to "Show", book_path(@book.id) %> |
  <%= link_to "Back", books_path %>
</p>

<% end %>

  </div>
 </div>
</div>

app/views/books/index.html.erb
<%= render 'books/list', user: @user, book: @book %>

 <div class="col-md-8 offset-md-1">

  <h1>Books</h1>

  <table class="table table-hover table-inverse">
  <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td>
      <%= link_to user_path(book.user_id) do %>
      <%= image_tag book.user.get_profile_image(100,100) %>
    　<% end %>
    </td>
    <td> <%= link_to book.title, book_path(book.id) %></td>
    <td> <%= book.body %></td>
  </tr>
  <% end %>
  </table>
  </div>

</div>
</div>

app/views/books/show.html.erb
<%= render 'books/list', user: @user, book: @new %>

  <div class="col-md-8 offset-md-1">

  <h1>Book detail</h1>

  <table class="table">
  <tr>
  <td>
    <%= link_to user_path(@user.id) do %>
    <%= image_tag @book.user.get_profile_image(100,100) %>
    <% end %>
  </td>
  <td scope="col"><%= link_to @book.title, book_path(@book.id) %>　</td>
  <td scope="col"><%= @book.body %>　</td>
  <% if current_user.id == @book.user_id%>
  <td><%= link_to "Edit", edit_book_path(@book.id) %>　</td>
  <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか?" %></td>
  <% end %>

  </tr>
  </tr>
  <tr><td><p><%= link_to @book.user.name, user_path(@user.id) %></p></td></tr>
  </table>
  </div>

</div>
</div>

app/views/homes/about.erb
<p></p>
<div class="container">
 <div class="row">
  <h1 class="px-3 mx-auto">Welcome
   <i class="fas fa-book"></i>
   <strong>Bookers!</strong>
  </h1>
 </div>
</div>

app/views/homes/top.html.erb
<div class="container">
 <div class="row">
   <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>welcome to
    <i class="fas fa-book"></i>
    <strong>Bookers !!</strong></h1>
    <p>In
    <i class="fas fa-book"></i>
    <strong>Bookers,</strong></p>

    <p>you can share and exchange your opinions , inpressions , and emotions</p>

    <p>about various books!</p>

    <div class="btn-wrapper col-10 mx-auto">

    <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
<%#<p class="btn btn-info btn-sm btn-block mb-3 sign_in"><%= link_to "Sign up", new_user_registration_path %>
    <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>

<%#<p><%= link_to "Log in", new_user_session_path %>
 </div>

   </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
          <span>Bookers</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

       <% if user_signed_in? %>
        <li>
         <%= link_to user_path(current_user.id),class:"nav-link text-light" do %>
          <i class="fas fa-home"></i>
          Home
         <% end %>
        </li>
        <li>
          <%= link_to users_path,class:"nav-link text-light" do %>
          <i class="fas fa-users"></i>
          Users
          <% end %>
        </li>
        <li>
          <%= link_to books_path, class:"nav-link text-light" do %>
          <i class="fas fa-book-open"></i>
          Books
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
          <i class="fas fa-sign-out-alt"></i>
          Log out
          <% end %>
        </li>

        <% else %>

        <li>
          <%= link_to root_path,class:"nav-link text-light" do %>
          <i class="fas fa-home"></i>
          Home
          <% end %>
        </li>
        <li>
          <%= link_to about_path,class:"nav-link text-light" do %>
          <i class="fas fa-link"></i>
          About
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
          <i class="fas fa-user-plus"></i>
          Sign up
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path, class:"nav-link text-light" do %>
          <i class="fas fa-sign-in-alt"></i>
          Log in
          <% end %>
          </a>
        </li>
       <% end %>

      </ul>
     </div>
     </div>
    </nav>
    </header>

    <% flash.each do |message_type, message|%>
    <div class="alert alert-<%= message_type%>"><%= message %></div>
    <% end %>

  <%= yield %>
  </body>

  <footer>
    <br><br>
   <p class="text-center">CopyRight Infratop.inc</p>

  </foote>


</html>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %> error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user, url: user_path(@user.id), method: :patch do |user| %>
<p>Name</p>
<%= user.text_field :name %>
<p>Image</p>

  <%= user.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*" %>
<p>Introduction</p>
<%= user.text_area :introduction %>
<br>
<%#= user.submit 'Update User' %>
<input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">

<% end %>

  </div>
 </div>
</div>

app/views/users/index.html.erb
<%= render 'books/list', user: @user, book: @book %>

<div class="col-md-8 offset-md-1">

<h1>Users</h1>
<!-- ユーザーの投稿一覧 -->
<table class="table">
  <tr>
    <th>image</th>
    <th>name</th>
  <tr>

<% @users.each do |user| %>

  <tr>
  <td><%= image_tag user.get_profile_image(100,100) %></td>
  <td><%= user.name %></td>
  <td><%= link_to "Show", user_path(user.id) %></td>
  </tr>
<% end %>

</table>

</div>
</div>
</div>

app/views/users/show.html.erb
<%= render 'books/list', user: @user, book: @new %>

<div class="col-md-8 offset-md-1">

<h1>Books</h1>

<table class="table">
  <tr>
    <th></th>
    <th scope="col">Title</th>
    <th scope="col">Opinion</th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td>
      <%= link_to user_path(@user.id) do %>
      <%= image_tag @user.get_profile_image(100,100) %>
      <% end %>
      </td>
    <td><%= link_to book.title, book_path(book.id) %></td>
    <td><%= book.body %></td>
  </tr>
  <% end %>
</table>

</div>
</div>
</div>